from .evaluate import evaluate
from .train_or_restore_predictor import train_or_restore_predictor
from .train_or_restore_predictor_adam import train_or_restore_predictor_adam
from .train_or_restore_cifar_10_gan import train_or_restore_cifar_10_gan
from .train_or_restore_cifar_100_90_classes_gan import train_or_restore_cifar_100_90_classes_gan
from .train_or_restore_cifar_100_40_classes_gan import train_or_restore_cifar_100_40_classes_gan
from .train_or_restore_cifar_10_vae import train_or_restore_cifar_10_vae
from .train_or_restore_cifar_100_6_classes_gan import train_or_restore_cifar_100_6_classes_gan
from .train_or_restore_cifar_100_10_classes_gan import train_or_restore_cifar_100_10_classes_gan

